name: Ora
favicon: null
layout_spectrum: 0.8561637650709599
typography_spectrum: 1
title: A Movement For Change
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6ec264'
    - '#e6e6e6'
    - '#414143'
    - '#616161'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
