name: Ora
favicon: null
layout_spectrum: 0.8561637650709599
typography_spectrum: 0.7161854729056358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8362286437768489
  lightness: 0.5832791079301387
  saturation: 0.2749285532627255
  rhythmicContrast: 0.7319924510084093
purpose: []
